# This is a basic workflow to help you get started with Actions

name: Build and run unit tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "testing", "development" ]
  pull_request:
    branches: [ "main", "testing", "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - run: sudo apt-get update -qq
      - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -qq cmake build-essential python3-pip python3-virtualenv nodejs tar gzip libpthread-stubs0-dev libc6-dbg gdb g++-12
      - run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 1200
      - run: g++ --version
      - name: Create build directory
        run: mkdir cmake-build-test
      - name: Build tests
        run: |
          cmake -DCMAKE_BUILD_TYPE=Test ..
          cmake --build .
        working-directory: cmake-build-test
      - name: Run tests
        run: ctest --output-on-failure
        working-directory: cmake-build-test
